// 文件：describer-go/code/code.go —— cod-code 插件：源码语言 / import 提取 / TODO / 生成标记 / 包名 / 函数数 / 注释率 / 测试文件 / 许可证 / 导出名
// 修改：2026-09-05（日期由 fresh-header.ps1 刷新）

// Package code cod-code 插件：源码文件的确定性事实。
// 字段字典见 docs/元数据字段说明.md 第 4.4 节。
package code

import (
	"path/filepath"
	"regexp"
	"strings"

	"github.com/Reisentyann/Mabel-s-Tentacles/describer-go"
)

func init() { describer.Register(descriptor{}) }

type descriptor struct{}

var codeLangs = map[string]string{
	".go": "go", ".py": "python", ".js": "javascript", ".ts": "typescript",
	".jsx": "javascript", ".tsx": "typescript", ".java": "java",
	".c": "c", ".h": "c", ".cpp": "cpp", ".hpp": "cpp", ".cc": "cpp",
	".rs": "rust", ".rb": "ruby", ".php": "php", ".sql": "sql",
	".sh": "shell", ".vue": "vue", ".css": "css", ".scss": "scss",
	".html": "html", ".swift": "swift", ".kt": "kotlin",
}

func (descriptor) Family() string { return "code" }

// FamilyVersion=2：v1 首发（lang/imports/todo-count）；
// v2 增补 P2 字段 7 个（字段字典 4.4 节）：generated/package/func-count/
// comment-ratio/test-file/license/exported-names。
func (descriptor) FamilyVersion() int     { return 2 }
func (descriptor) SPNamespaces() []string { return nil }
func (descriptor) Supports(path string, _ []byte, b describer.Basic) bool {
	if !b.Textish {
		return false
	}
	_, ok := codeLangs[strings.ToLower(filepath.Ext(path))]
	return ok
}

var (
	reGoImport    = regexp.MustCompile(`(?m)^\s*import\s+(?:_\s+|\w+\s+)?"([^"]+)"`)
	reGoBlock     = regexp.MustCompile(`(?m)^\s*"([^"]+)"\s*$`)
	reESFrom      = regexp.MustCompile(`(?m)^\s*(?:import|export)\s+[^\n]*?from\s+["']([^"']+)["']`)
	reESImport    = regexp.MustCompile(`(?m)^\s*import\s+["']([^"']+)["']`)
	reRequire     = regexp.MustCompile(`(?m)^\s*(?:const|let|var)\s+\w+(?:\s*=\s*)?\w*\s*=\s*require\(\s*["']([^"']+)["']`)
	rePyFrom      = regexp.MustCompile(`(?m)^\s*from\s+([\w.]+)\s+import\b`)
	rePyImport    = regexp.MustCompile(`(?m)^\s*import\s+([\w.]+)`)
	reCInclude    = regexp.MustCompile(`(?m)^\s*#\s*include\s+[<"]([^>"]+)[>"]`)
	reTODO        = regexp.MustCompile(`(?i)\b(TODO|FIXME)\b`)
	reGoImportBlk = regexp.MustCompile(`(?s)import\s*\(([^)]*)\)`)

	reGenerated = regexp.MustCompile(`(?i)(code generated|auto-generated|automatically generated|do not edit|generated by)`)
	reGoPkg     = regexp.MustCompile(`(?m)^package\s+(\w+)`)
	reGoFunc    = regexp.MustCompile(`(?m)^func\s+`)
	rePyFunc    = regexp.MustCompile(`(?m)^\s*(?:def|class)\s+`)
	reJSFunc    = regexp.MustCompile(`(?m)^\s*(?:export\s+)?(?:async\s+)?function\s+\w+`)
	reJSArrow   = regexp.MustCompile(`(?m)^\s*(?:const|let|var)\s+\w+\s*=\s*(?:async\s*)?\(`)
	reRustFunc  = regexp.MustCompile(`(?m)^\s*(?:pub\s+)?fn\s+`)
	// c 系函数计数：逐行启发式（返回类型 名字(参数) { 形态），误报可接受
	reCFunc    = regexp.MustCompile(`^\s*\w[\w<>\[\]*&\s]*\s+\w+\s*\([^;{]*\)\s*\{?\s*$`)
	reLicense  = regexp.MustCompile(`(?i)(MIT License|Apache License|GPL|BSD|Mozilla Public|SPDX-License-Identifier:\s*(\S+))`)
	reGoExport = regexp.MustCompile(`(?m)^(?:func|type|var|const)\s+([A-Z]\w*)`)
	rePyExport = regexp.MustCompile(`(?m)^(?:def|class)\s+([A-Za-z_]\w*)`)
)

func (descriptor) Analyze(in describer.Input, full []byte) (map[string]any, map[string]string) {
	src := string(full)
	lang := codeLangs[strings.ToLower(filepath.Ext(in.Path))]
	a := map[string]any{
		"cod-code-lang":       lang,
		"cod-code-todo-count": len(reTODO.FindAllString(src, -1)),
		"cod-code-generated":  generatedMarked(src),
		"cod-code-test-file":  testFile(in.Path, lang),
	}
	if imports := extractImports(lang, src); len(imports) > 0 {
		a["cod-code-imports"] = imports
	}
	if pkg := packageName(lang, src); pkg != "" {
		a["cod-code-package"] = pkg
	}
	if n, ok := funcCount(lang, src); ok {
		a["cod-code-func-count"] = n
	}
	if r, ok := commentRatio(lang, src); ok {
		a["cod-code-comment-ratio"] = r
	}
	if lic := licenseName(src); lic != "" {
		a["cod-code-license"] = lic
	}
	if names := exportedNames(lang, src); len(names) > 0 {
		a["cod-code-exported-names"] = names
	}
	return a, nil
}

// generatedMarked 自动生成文件标记：前 5 行匹配生成标记（"Code generated ... DO NOT EDIT" 等）。
func generatedMarked(src string) bool {
	head := firstLines(src, 5)
	return reGenerated.MatchString(head)
}

// packageName 包名声明（仅 go 语言产；跨文件推断不做）。
func packageName(lang, src string) string {
	if lang != "go" {
		return ""
	}
	if m := reGoPkg.FindStringSubmatch(src); m != nil {
		return m[1]
	}
	return ""
}

// funcCount 函数/类定义计数，按语言正则；无对应正则的语言不产（缺失即未分析）。
// c 系为逐行启发式（返回类型 名字(参数) {），误报可接受。
func funcCount(lang, src string) (int, bool) {
	switch lang {
	case "go":
		return len(reGoFunc.FindAllString(src, -1)), true
	case "python":
		return len(rePyFunc.FindAllString(src, -1)), true
	case "javascript", "typescript":
		return len(reJSFunc.FindAllString(src, -1)) + len(reJSArrow.FindAllString(src, -1)), true
	case "rust":
		return len(reRustFunc.FindAllString(src, -1)), true
	case "c", "cpp", "java", "kotlin", "swift":
		n := 0
		for _, l := range strings.Split(src, "\n") {
			if reCFunc.MatchString(strings.TrimRight(l, "\r")) {
				n++
			}
		}
		return n, true
	}
	return 0, false
}

// commentRatio 注释行 / 有效行（非空行）。行注释前缀按语言；分母 0 不产。
func commentRatio(lang, src string) (float64, bool) {
	var comment, effective int
	for _, raw := range strings.Split(src, "\n") {
		l := strings.TrimSpace(strings.TrimRight(raw, "\r"))
		if l == "" {
			continue
		}
		effective++
		switch lang {
		case "go", "c", "cpp", "java", "javascript", "typescript",
			"rust", "kotlin", "swift", "vue":
			if strings.HasPrefix(l, "//") {
				comment++
			}
		case "python", "ruby", "shell":
			if strings.HasPrefix(l, "#") {
				comment++
			}
		case "css", "scss":
			if strings.Contains(l, "/*") {
				comment++
			}
		case "sql":
			if strings.HasPrefix(l, "--") {
				comment++
			}
		}
	}
	if effective == 0 {
		return 0, false
	}
	return describer.Round2(float64(comment) / float64(effective)), true
}

// testFile 测试文件判定（文件名模式，按语言）。
func testFile(path, lang string) bool {
	base := strings.ToLower(filepath.Base(path))
	switch lang {
	case "go":
		return strings.HasSuffix(base, "_test.go")
	case "python":
		return strings.HasPrefix(base, "test_") || strings.HasSuffix(base, "_test.py")
	case "javascript", "typescript":
		return strings.Contains(base, ".test.") || strings.Contains(base, ".spec.")
	}
	return false
}

// licenseName 许可证识别：前 10 行，SPDX 标识符优先，其次关键词；截 40 字符。
func licenseName(src string) string {
	head := firstLines(src, 10)
	m := reLicense.FindStringSubmatch(head)
	if m == nil {
		return ""
	}
	name := m[1]
	if len(m) >= 3 && strings.TrimSpace(m[2]) != "" {
		name = m[2] // SPDX-License-Identifier: <id> → 产标识符
	}
	return describer.TrimRunes(strings.TrimRight(name, "*.,;"), 40)
}

// exportedNames 前 10 个导出符号名（go 大写导出 / python 公开 def·class），去重保序。
func exportedNames(lang, src string) []string {
	var raw [][]string
	switch lang {
	case "go":
		raw = reGoExport.FindAllStringSubmatch(src, -1)
	case "python":
		raw = rePyExport.FindAllStringSubmatch(src, -1)
	default:
		return nil
	}
	const maxN = 10
	seen := map[string]bool{}
	var out []string
	for _, m := range raw {
		if len(m) < 2 {
			continue
		}
		name := m[1]
		if lang == "python" && strings.HasPrefix(name, "_") {
			continue // 下划线私有约定
		}
		if seen[name] {
			continue
		}
		seen[name] = true
		out = append(out, name)
		if len(out) >= maxN {
			break
		}
	}
	return out
}

// firstLines 取前 n 行（用于头部标记类判定）。
func firstLines(src string, n int) string {
	lines := strings.SplitN(src, "\n", n+1)
	return strings.Join(lines[:min(n, len(lines))], "\n")
}

// extractImports 提取前 10 条 import/require/include（去重保序）。
func extractImports(lang, src string) []string {
	var raw [][]string
	switch lang {
	case "go":
		raw = append(raw, reGoImport.FindAllStringSubmatch(src, -1)...)
		if blk := reGoImportBlk.FindStringSubmatch(src); blk != nil {
			raw = append(raw, reGoBlock.FindAllStringSubmatch(blk[1], -1)...)
		}
	case "python":
		raw = append(raw, rePyFrom.FindAllStringSubmatch(src, -1)...)
		raw = append(raw, rePyImport.FindAllStringSubmatch(src, -1)...)
	case "c", "cpp":
		raw = append(raw, reCInclude.FindAllStringSubmatch(src, -1)...)
	default: // js 系 / php / ruby 等
		raw = append(raw, reESFrom.FindAllStringSubmatch(src, -1)...)
		raw = append(raw, reESImport.FindAllStringSubmatch(src, -1)...)
		raw = append(raw, reRequire.FindAllStringSubmatch(src, -1)...)
	}

	const maxN = 10
	seen := map[string]bool{}
	var out []string
	for _, m := range raw {
		if len(m) < 2 {
			continue
		}
		mod := strings.TrimSpace(m[1])
		if mod == "" || seen[mod] {
			continue
		}
		seen[mod] = true
		out = append(out, mod)
		if len(out) >= maxN {
			break
		}
	}
	return out
}
