// 文件：describer-go/code/code_test.go —— cod-code 单元测试（含 v2：generated/package/func-count/comment-ratio/test-file/license/exported-names）
// 修改：2026-09-05（日期由 fresh-header.ps1 刷新）

package code

import (
	"reflect"
	"testing"

	"github.com/Reisentyann/Mabel-s-Tentacles/describer-go"
)

const goSrc = `package main

import "fmt"
import (
	"os"
	"strings"
)

// TODO: fix me
func main() {
	// FIXME: later
	fmt.Println(strings.Join(os.Args, " "))
}
`

func TestGoAnalyze(t *testing.T) {
	d := descriptor{}
	attrs, _ := d.Analyze(describer.Input{Path: "main.go"}, []byte(goSrc))

	if attrs["cod-code-lang"] != "go" {
		t.Fatalf("lang = %v", attrs["cod-code-lang"])
	}
	if got := attrs["cod-code-imports"].([]string); !reflect.DeepEqual(got, []string{"fmt", "os", "strings"}) {
		t.Fatalf("imports = %#v", got)
	}
	if attrs["cod-code-todo-count"].(int) != 2 {
		t.Fatalf("todo-count = %v, want 2", attrs["cod-code-todo-count"])
	}
}

func TestSupports(t *testing.T) {
	d := descriptor{}
	if !d.Supports("x.go", nil, describer.Basic{Textish: true}) {
		t.Fatal("go file should be supported")
	}
	if d.Supports("x.md", nil, describer.Basic{Textish: true}) {
		t.Fatal("markdown should not be code")
	}
	if d.Supports("x.go", nil, describer.Basic{Textish: false}) {
		t.Fatal("non-textish must not be code")
	}
}

func TestP2GeneratedAndPackage(t *testing.T) {
	d := descriptor{}
	// 普通源：generated=false、package=main
	attrs, _ := d.Analyze(describer.Input{Path: "main.go"}, []byte(goSrc))
	if attrs["cod-code-generated"] != false {
		t.Fatalf("generated = %v, want false", attrs["cod-code-generated"])
	}
	if attrs["cod-code-package"] != "main" {
		t.Fatalf("package = %v, want main", attrs["cod-code-package"])
	}

	// 生成标记：首行 DO NOT EDIT → true
	gen := "// Code generated by protoc-gen-go. DO NOT EDIT.\n// source: a.proto\n\npackage pb\n\nfunc Unmarshal() {}\n"
	attrs, _ = d.Analyze(describer.Input{Path: "gen.go"}, []byte(gen))
	if attrs["cod-code-generated"] != true {
		t.Fatalf("generated = %v, want true", attrs["cod-code-generated"])
	}
	if attrs["cod-code-package"] != "pb" {
		t.Fatalf("package = %v, want pb", attrs["cod-code-package"])
	}
}

func TestP2FuncCountAndCommentRatio(t *testing.T) {
	d := descriptor{}
	attrs, _ := d.Analyze(describer.Input{Path: "main.go"}, []byte(goSrc))
	// goSrc：1 个 func
	if got := attrs["cod-code-func-count"].(int); got != 1 {
		t.Fatalf("func-count = %v, want 1", got)
	}
	// goSrc：11 个非空行中 2 个 // 注释行 → 0.18
	if got := attrs["cod-code-comment-ratio"].(float64); got != 0.18 {
		t.Fatalf("comment-ratio = %v, want 0.18", got)
	}

	// python：def+class 计数、# 注释
	py := "import os\n\n# comment\ndef foo():\n    pass\n\nclass Bar:\n    pass\n"
	attrs, _ = d.Analyze(describer.Input{Path: "m.py"}, []byte(py))
	if got := attrs["cod-code-func-count"].(int); got != 2 {
		t.Fatalf("py func-count = %v, want 2", got)
	}
	// py 非空行 6，注释 1 → 0.17
	if got := attrs["cod-code-comment-ratio"].(float64); got != 0.17 {
		t.Fatalf("py comment-ratio = %v, want 0.17", got)
	}
}

func TestP2TestFile(t *testing.T) {
	d := descriptor{}
	cases := map[string]bool{
		"foo_test.go":   true,
		"main.go":       false,
		"test_utils.py": true,
		"utils_test.py": true,
		"app.spec.ts":   true,
		"app.ts":        false,
	}
	for path, want := range cases {
		attrs, _ := d.Analyze(describer.Input{Path: path}, []byte("x\n"))
		if got := attrs["cod-code-test-file"].(bool); got != want {
			t.Errorf("test-file(%q) = %v, want %v", path, got, want)
		}
	}
}

func TestP2License(t *testing.T) {
	d := descriptor{}
	lic := "// MIT License\n//\n// Copyright 2026\npackage main\n\nfunc F() {}\n"
	attrs, _ := d.Analyze(describer.Input{Path: "m.go"}, []byte(lic))
	if attrs["cod-code-license"] != "MIT License" {
		t.Fatalf("license = %v, want MIT License", attrs["cod-code-license"])
	}

	spdx := "// SPDX-License-Identifier: MIT\npackage main\n"
	attrs, _ = d.Analyze(describer.Input{Path: "m.go"}, []byte(spdx))
	if attrs["cod-code-license"] != "MIT" {
		t.Fatalf("spdx license = %v, want MIT", attrs["cod-code-license"])
	}

	attrs, _ = d.Analyze(describer.Input{Path: "m.go"}, []byte(goSrc))
	if _, ok := attrs["cod-code-license"]; ok {
		t.Fatal("无许可证头不应产键")
	}
}

func TestP2ExportedNames(t *testing.T) {
	d := descriptor{}
	src := `package main

func Foo() {}
func bar() {}
type Bar struct{}
const Qux = 1
var Zed int
`
	attrs, _ := d.Analyze(describer.Input{Path: "m.go"}, []byte(src))
	got, _ := attrs["cod-code-exported-names"].([]string)
	if !reflect.DeepEqual(got, []string{"Foo", "Bar", "Qux", "Zed"}) {
		t.Fatalf("exported-names = %#v, want [Foo Bar Qux Zed]", got)
	}

	// main.go 全小写 → 不产
	attrs, _ = d.Analyze(describer.Input{Path: "main.go"}, []byte(goSrc))
	if _, ok := attrs["cod-code-exported-names"]; ok {
		t.Fatal("无导出符号不应产键")
	}

	// python：公开 def/class，下划线私有剔除
	py := "def public_fn():\n    pass\n\nclass MyClass:\n    pass\n\ndef _private():\n    pass\n"
	attrs, _ = d.Analyze(describer.Input{Path: "m.py"}, []byte(py))
	got, _ = attrs["cod-code-exported-names"].([]string)
	if !reflect.DeepEqual(got, []string{"public_fn", "MyClass"}) {
		t.Fatalf("py exported-names = %#v, want [public_fn MyClass]", got)
	}
}
